In [2]:
import numpy as np

In [3]:
type(np.array([1,2,3,4]))

numpy.ndarray

In [4]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [5]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
a=np.random.randint(10,size=4)

In [7]:
a.ndim

1

In [8]:
a.shape

(4,)

In [9]:
a.size

4

In [10]:
a.dtype

dtype('int64')

In [27]:
a=np.random.randint(10,size=9)

In [28]:
a

array([1, 7, 9, 8, 5, 4, 4, 0, 4])

In [20]:
ar = a.reshape(3,3)

In [21]:
ar

array([[2, 3, 6],
       [7, 5, 8],
       [2, 8, 9]])

In [23]:
ar[1:3,0:2]

array([[7, 5],
       [2, 8]])

In [32]:
ar.reshape(1,9)

array([[2, 3, 6, 7, 5, 8, 2, 8, 9]])

In [35]:
del ar

In [37]:
a

array([1, 7, 9, 8, 5, 4, 4, 0, 4])

In [39]:
catch = [2,5,7]
a[catch]

array([9, 4, 0])

In [40]:
a < 5

array([ True, False, False, False, False,  True,  True,  True,  True])

In [41]:
a[a<5]

array([1, 4, 4, 0, 4])

In [42]:
new = np.array([2,4,6,8])

In [43]:
new

array([2, 4, 6, 8])

In [44]:
print(new)

[2 4 6 8]


In [45]:
print(new**2)

[ 4 16 36 64]


In [47]:
np.arange(1,7)

array([1, 2, 3, 4, 5, 6])